
# Config for DevContainers: https://containers.dev/guide/dockerfile#docker-compose

services:
  devcontainer:
    image: "mcr.microsoft.com/devcontainers/python:1-3.11-bookworm"
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    # network_mode: service:influxdb

  influxdb:
    image: influxdb:2.5.1-alpine
    volumes:
      - influxdb-data:/var/lib/influxdb2
      - influxdb-data:/etc/influxdb2
      - ./.env_dev:/workspaces/src/.env:cached
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USER:-admin}  # Default to 'admin'
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminadmin
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG:?Missing InfluxDB ORG for initial setup!}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUX_BUCKET?:Missing Influx Bucket for initial setup!}
      - DOCKER_INFLUXDB_INIT_RETENTION=1w
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_TOKEN:-WQox-nqj_1_WSSzunUrKe8keVE-NT950Lwfs6u-m03VnQ==}  # Default value
    ports:
      - "8086:${INFLUXDB_PORT}"

volumes:
  influxdb-data:
